### ISSUE TITLE
'MQTTPlugin' object has no attribute '_latest_action'

### ISSUE THREAD

**Issue by jdodgen** [n8henrie/fauxmo-plugins#32]
fauxmo v0.8.0
mqttplugin.py  my paho-mqtt 2.0.0 patch version  https://github.com/jdodgen/fauxmo-plugins/commit/8835fe59d01e99d9d4ac95a7884a60cee6b60bde
Raspbian
 
I had not done any "discover devices" for a while
But when rebuilding a system with new stuff. I get this error when testing.
```
'MQTTPlugin' object has no attribute '_latest_action'
```
it is related to:
``` 
    if self.use_fake_state is True:
       return super().get_state()
```
This can be repeated just by doing another "discover devices" 
```
{
    "FAUXMO": {
        "ip_address": "auto"
    },
    "PLUGINS": {
        "MQTTPlugin": {
            "path": "mqttplugin.py",
            "DEVICES": [
                {
                    "port": 56000,
                    "name": "desk light",
                    "on_cmd": [ "zigbee2mqtt/led on desk/set", "{\"state\": \"ON\"}" ],
                    "off_cmd": [ "zigbee2mqtt/led on desk/set", "{\"state\": \"OFF\"}" ],
                    "mqtt_server": "192.168.0.173",
                    "mqtt_port": 1883,
                    "use_fake_state": true,
                    "initial_state": "off"
                }
            ]
        }
    }
}
```

Trace
```
<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetBinaryState xmlns:u="urn:Belkin:service:basicevent:1"><BinaryState>1</BinaryState></u:GetBinaryState></s:Body></s:Envelope>
2024-04-25 15:02:30 fauxmo:69       INFO     request BasicEvent1
2024-04-25 15:02:30 fauxmo:122      DEBUG    Handling action for plugin type MQTTPlugin(on_cmd='zigbee2mqtt/led on desk/set', on_value='{"state": "ON"}', off_cmd='zigbee2mqtt/led on desk/set', off_value='{"state": "OFF"}', state_cmd=None, status='unknown', _subscribed=False, initial_state=None, use_fake_state=True, client=<paho.mqtt.client.Client object at 0xffff92b8c7d0>, _name='desk light', _port=56000)
2024-04-25 15:02:30 fauxmo:151      INFO     Attempting to get state for desk light
2024-04-25 15:02:30 asyncio:1771     ERROR    Fatal error: protocol.data_received() call failed.
handle_traceback: Handle created at (most recent call last):
  File "/usr/local/bin/fauxmo", line 8, in <module>
    sys.exit(cli())
  File "/home/jim/.local/lib/python3.11/site-packages/fauxmo/cli.py", line 45, in cli
    main(config_path_str=args.config, verbosity=verbosity)
  File "/home/jim/.local/lib/python3.11/site-packages/fauxmo/fauxmo.py", line 165, in main
    loop.run_forever()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 893, in _add_reader
    self._loop._add_reader(fd, callback, *args)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 263, in _add_reader
    handle = events.Handle(callback, args, self, None)
protocol: <fauxmo.protocols.Fauxmo object at 0xffff91ea9390>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/home/jim/.local/lib/python3.11/site-packages/fauxmo/protocols.py", line 70, in data_received
    self.handle_action(msg)
  File "/home/jim/.local/lib/python3.11/site-packages/fauxmo/protocols.py", line 156, in handle_action
    state = self.plugin.get_state().casefold()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/mqttplugin.py", line 228, in get_state
    return super().get_state()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jim/.local/lib/python3.11/site-packages/fauxmo/plugins/__init__.py", line 98, in get_state
    return self.latest_action
           ^^^^^^^^^^^^^^^^^^
  File "/home/jim/.local/lib/python3.11/site-packages/fauxmo/plugins/__init__.py", line 64, in __getattribute__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/.local/lib/python3.11/site-packages/fauxmo/plugins/__init__.py", line 111, in latest_action
    return self._latest_action
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jim/.local/lib/python3.11/site-packages/fauxmo/plugins/__init__.py", line 64, in __getattribute__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MQTTPlugin' object has no attribute '_latest_action'
2024-04-25 15:02:31 asyncio:167      DEBUG    <Server sockets=(<asyncio.TransportSocket fd=8, family=2, type=1, proto=6, laddr=('192.168.0.173', 56000)>,)> got a new connection from ('192.168.0.205', 44628): <socket.socket fd=12, family=2, type=1, proto=6, laddr=('192.168.0.173', 56000), raddr=('192.168.0.205', 44628)>
2024-04-25 15:02:31 fauxmo:46       DEBUG    Connection made with: ('192.168.0.205', 44628)
2024-04-25 15:02:31 fauxmo:58       DEBUG    Received message:
POST /upnp/control/basicevent1 HTTP/1.1
Host: 192.168.0.173:56000
```

**Comment by n8henrie** [comment]
I think something is off in your configuration.

The config you provided above specifies `"initial_state": "off"`, but the log output you included shows `initial_state=None`.

**Comment by n8henrie** [comment]
When I use the same configuration as you've provided above, I see in my log `'initial_state': 'off'`.

**Comment by n8henrie** [comment]
Hmm, nevermind -- I'm seeing the same error logged when I actually discover devices. Thanks for bringing this to my attention.

**Comment by n8henrie** [comment]
Same issue as https://github.com/n8henrie/fauxmo/commit/51c1a35bb03f7ce06acf13726a97adceb4e72bb5 -- fix incoming

EDIT: Going to hold off on a fix until your PR is ready for merge -- thank you!

**Comment by jdodgen** [comment]
thanks, kind of a weird bug.
